"""The parametric part library.

This is where the design principle lives. Nothing here is generated by a model: each part
is a named mechanism with a fixed topology and a handful of dimensions, and building one is
a deterministic function of those dimensions. A model's only role, in `propose.py`, is to
choose which mechanism and fill in the numbers.

That is what makes the co-design side of the pipeline stable. A model that writes geometry
code fails in unbounded ways — it does not compile, it compiles into something non-manifold,
or it compiles into something that cannot be made. A model that fills in eight floats can
only fail in one way, which pydantic catches before any geometry is built, and which the
manufacturability check in `dfm.py` catches for the rest.

Each part produces three things at once: a watertight mesh for printing and for the visual,
an explicit decomposition into primitives for collision, and named frames for the interfaces
it mates against. The primitive collision model matters — a convex hull of a bracket is not
a bracket, and a mesh collider of one is slow and unstable, whereas four boxes are both fast
and exactly right.
"""

from __future__ import annotations

import math
from abc import ABC, abstractmethod
from typing import Annotated, Literal

import numpy as np
import trimesh
from pydantic import BaseModel, ConfigDict, Field, model_validator

from amx.codesign.materials import DEFAULT_MATERIAL, Material, material
from amx.geometry import Pose, matrix_to_quat

BOOLEAN_ENGINE = "manifold"

FEATHER_EDGE_LIMIT_RAD = math.pi / 4.0
"""Shallowest angle at which a hole may break through a face.

Where a bore meets a face it is not perpendicular to, the material runs out to a point. At
45 deg the resulting edge is still an edge; much below that it is a feather that chips off a
machined part and simply does not print.
"""

BOOLEAN_OVERSHOOT = 5e-5
"""How far volumes are made to overlap before a boolean.

Exact coplanar or tangent surfaces are what makes a mesh boolean produce a non-manifold or
split result, and 50 um is far below anything a machine will resolve.
"""


class Primitive(BaseModel):
    """One convex collision volume, in the part's own frame."""

    model_config = ConfigDict(extra="forbid")

    shape: Literal["box", "cylinder", "sphere", "capsule"]
    size: tuple[float, ...] = Field(
        description="MJCF `size` semantics: box half-extents, cylinder (radius, half-length), "
        "sphere (radius), capsule (radius, half-length)."
    )
    pose: Pose = Field(default_factory=Pose)
    role: str = Field(
        default="",
        description="What this volume is, in the template's own terms — `floor`, `wall`, "
        "`jaw`. Becomes the geom's name, which is how a plan can say 'the part must touch "
        "the well floor' and how the judge can measure insertion depth. Without it the "
        "collision set is an unlabelled pile of boxes and no rule can refer to any of it.",
    )

    def volume(self) -> float:
        match self.shape:
            case "box":
                return 8.0 * self.size[0] * self.size[1] * self.size[2]
            case "cylinder":
                return math.pi * self.size[0] ** 2 * 2.0 * self.size[1]
            case "sphere":
                return 4.0 / 3.0 * math.pi * self.size[0] ** 3
            case "capsule":
                return math.pi * self.size[0] ** 2 * 2.0 * self.size[1] + (
                    4.0 / 3.0 * math.pi * self.size[0] ** 3
                )
        raise ValueError(self.shape)

    def minimum_extent(self) -> float:
        match self.shape:
            case "box":
                return 2.0 * min(self.size[:3])
            case "cylinder" | "capsule":
                return 2.0 * self.size[0]
            case "sphere":
                return 2.0 * self.size[0]
        raise ValueError(self.shape)


class PartGeometry(BaseModel):
    """Everything downstream needs from a built part."""

    model_config = ConfigDict(extra="forbid", arbitrary_types_allowed=True)

    part_id: str
    template: str
    mesh: trimesh.Trimesh
    collision: list[Primitive]
    frames: dict[str, Pose] = Field(
        default_factory=dict,
        description="Named interfaces, exported as MJCF sites so the plan can target them.",
    )
    material: Material
    parameters: dict[str, float] = Field(default_factory=dict)
    stated_clearances: dict[str, float] = Field(
        default_factory=dict,
        description="Fits the part claims to provide, checked against the material's allowance.",
    )

    @property
    def mass_kg(self) -> float:
        return self.material.mass_of(float(self.mesh.volume))

    @property
    def extents_m(self) -> tuple[float, float, float]:
        return tuple(float(v) for v in self.mesh.extents)  # type: ignore[return-value]


class Part(BaseModel, ABC):
    """Base for every template. Subclasses declare parameters and implement `build`."""

    model_config = ConfigDict(extra="forbid")

    part_id: str = Field(pattern=r"^[a-z0-9][a-z0-9_]*$")
    material_key: str = Field(default=DEFAULT_MATERIAL.key)

    @property
    def material(self) -> Material:
        return material(self.material_key)

    @abstractmethod
    def build(self) -> PartGeometry: ...

    def _finish(
        self,
        mesh: trimesh.Trimesh,
        collision: list[Primitive],
        frames: dict[str, Pose],
        *,
        clearances: dict[str, float] | None = None,
    ) -> PartGeometry:
        # Merge coincident vertices, but do not let trimesh "validate": that drops degenerate
        # faces, and a sliver triangle left by a boolean is often the only thing closing a
        # corner. Removing it turns a watertight solid into one with a hole. A 20 um sliver
        # bothers neither a slicer nor MuJoCo; an open mesh bothers both.
        mesh.process(validate=False)
        return PartGeometry(
            part_id=self.part_id,
            template=self.template,  # type: ignore[attr-defined]
            mesh=mesh,
            collision=collision,
            frames=frames,
            material=self.material,
            parameters={
                k: float(v)
                for k, v in self.model_dump().items()
                if isinstance(v, (int, float)) and not isinstance(v, bool)
            },
            stated_clearances=clearances or {},
        )


# --------------------------------------------------------------------------- #
# Templates
# --------------------------------------------------------------------------- #


class FlangeAdapter(Part):
    """Bolts to the arm's tool flange and presents a new face, optionally offset and tilted.

    The most common thing a wetlab cell needs and the arm does not have: a way to hold a
    pipette, a probe, or a hook at an angle the wrist cannot reach on its own. Built as a
    base plate on the flange bolt circle, a riser, and a tool plate.
    """

    template: Literal["flange_adapter"] = "flange_adapter"

    flange_diameter_m: float = Field(default=0.063, gt=0.02, le=0.2)
    bolt_circle_diameter_m: float = Field(default=0.050, gt=0.01, le=0.18)
    bolt_count: int = Field(default=4, ge=3, le=12)
    bolt_diameter_m: float = Field(default=0.005, gt=0.002, le=0.012)
    centre_bore_diameter_m: float = Field(
        default=0.0315, ge=0.0, le=0.1, description="Cable pass-through. Zero for a solid plate."
    )
    plate_thickness_m: float = Field(default=0.006, gt=0.002, le=0.03)
    riser_length_m: float = Field(default=0.04, ge=0.0, le=0.25)
    riser_diameter_m: float = Field(default=0.042, gt=0.006, le=0.12)
    tool_plate_diameter_m: float = Field(default=0.050, gt=0.01, le=0.18)
    tilt_rad: float = Field(
        default=0.0, ge=-1.0472, le=1.0472, description="Tool face tilt about the Y axis."
    )

    @model_validator(mode="after")
    def dimensions_are_consistent(self) -> "FlangeAdapter":
        """Reject parameter sets that cannot describe this mechanism.

        Catching these here rather than in `dfm.py` is the point of the whole approach: a
        proposal that says something impossible is rejected before any geometry is built, so
        the failure is a validation message a model can act on instead of a broken mesh.
        """
        wall = self.material.minimum_wall_m
        if self.centre_bore_diameter_m > 0.0:
            riser_wall = (self.riser_diameter_m - self.centre_bore_diameter_m) / 2.0
            if riser_wall < wall:
                raise ValueError(
                    f"a {self.centre_bore_diameter_m * 1000:.1f} mm centre bore through a "
                    f"{self.riser_diameter_m * 1000:.1f} mm riser leaves a "
                    f"{riser_wall * 1000:.2f} mm wall, under the {wall * 1000:.2f} mm minimum "
                    f"for {self.material.label}. Widen the riser or narrow the bore."
                )
            # The bore is drilled up the riser's axis, so a tilted tool face crosses it at an
            # angle and the lip thins to nothing on one side.
            if abs(self.tilt_rad) > FEATHER_EDGE_LIMIT_RAD:
                raise ValueError(
                    f"the centre bore runs up the riser axis and would break through a tool "
                    f"face tilted {math.degrees(self.tilt_rad):.0f} deg at "
                    f"{90 - abs(math.degrees(self.tilt_rad)):.0f} deg, leaving a feather edge "
                    f"around the opening. Keep the tilt at or under "
                    f"{math.degrees(FEATHER_EDGE_LIMIT_RAD):.0f} deg, or set the centre bore to "
                    "zero and route the cable outside the adapter."
                )
        hole_radius = (self.bolt_diameter_m + self.material.hole_allowance_m) / 2.0
        edge = (self.flange_diameter_m - self.bolt_circle_diameter_m) / 2.0 - hole_radius
        if edge < wall:
            raise ValueError(
                f"the bolt circle leaves {edge * 1000:.2f} mm between the holes and the plate "
                f"rim, under the {wall * 1000:.2f} mm minimum. Shrink the bolt circle or widen "
                "the flange plate."
            )
        pitch = math.pi * self.bolt_circle_diameter_m / self.bolt_count
        if pitch - 2.0 * hole_radius < wall:
            raise ValueError(
                f"{self.bolt_count} holes on a {self.bolt_circle_diameter_m * 1000:.1f} mm bolt "
                "circle leave less material between neighbours than the minimum wall. Use fewer "
                "or smaller bolts."
            )
        # Tilting the tool plate foreshortens it: seen down the riser's axis it is an ellipse
        # narrowed to cos(tilt) of its diameter. Once that is narrower than the riser, the
        # riser breaks out through the rim and the two outlines cross in a feather edge.
        covered = self.tool_plate_diameter_m * math.cos(self.tilt_rad)
        if covered < self.riser_diameter_m:
            raise ValueError(
                f"a {math.degrees(self.tilt_rad):.0f} deg tilt narrows the "
                f"{self.tool_plate_diameter_m * 1000:.1f} mm tool plate to "
                f"{covered * 1000:.1f} mm across the riser, which is "
                f"{self.riser_diameter_m * 1000:.1f} mm wide, so the riser would break out "
                f"through the plate rim. Widen the tool plate to at least "
                f"{self.riser_diameter_m / math.cos(self.tilt_rad) * 1000:.1f} mm, narrow the "
                "riser, or reduce the tilt."
            )
        return self

    def build(self) -> PartGeometry:
        plate = trimesh.creation.cylinder(
            radius=self.flange_diameter_m / 2.0, height=self.plate_thickness_m
        )
        plate.apply_translation((0.0, 0.0, self.plate_thickness_m / 2.0))

        cuts: list[trimesh.Trimesh] = []
        hole_radius = (self.bolt_diameter_m + self.material.hole_allowance_m) / 2.0
        for index in range(self.bolt_count):
            angle = 2.0 * math.pi * index / self.bolt_count
            hole = trimesh.creation.cylinder(
                radius=hole_radius, height=self.plate_thickness_m * 3.0
            )
            hole.apply_translation(
                (
                    self.bolt_circle_diameter_m / 2.0 * math.cos(angle),
                    self.bolt_circle_diameter_m / 2.0 * math.sin(angle),
                    self.plate_thickness_m / 2.0,
                )
            )
            cuts.append(hole)
        if self.centre_bore_diameter_m > 0.0:
            bore = trimesh.creation.cylinder(
                radius=self.centre_bore_diameter_m / 2.0,
                height=(self.plate_thickness_m + self.riser_length_m) * 3.0,
            )
            cuts.append(bore)

        # An axial post with an angled face milled onto its top, which is how a bracket that
        # presents a tilted tool face is actually made. Two details keep the result solid at
        # every tilt: the post runs from inside the base plate up to the tool plate's own
        # mid-plane, so neither joint is a tangent contact — unioning volumes that merely
        # touch yields a split or non-manifold mesh that no slicer accepts — and the material
        # the post would otherwise leave sticking through the angled face is cut away, rather
        # than left as a feather edge that fails the wall check.
        plate_top = self.plate_thickness_m
        pivot_z = plate_top + self.riser_length_m
        post_bottom = plate_top / 2.0
        face_z = pivot_z + self.plate_thickness_m / 2.0
        post_radius = self.riser_diameter_m / 2.0

        # The post runs past the angled face and is trimmed flush with it. Stopping it at the
        # face's centre height instead would leave the post and the plate meeting in a knife
        # edge on the high side of the tilt, which is watertight but unmakeable.
        post_top = face_z + post_radius * abs(math.tan(self.tilt_rad)) + BOOLEAN_OVERSHOOT
        post = trimesh.creation.cylinder(radius=post_radius, height=post_top - post_bottom)
        post.apply_translation((0.0, 0.0, (post_bottom + post_top) / 2.0))

        # The plate is built slightly proud of its nominal top face and then trimmed back to
        # it, so the trimming plane crosses the plate's side wall instead of sitting on its
        # top face. Coplanar boolean surfaces are what produce the non-manifold results here,
        # and the finished thickness still comes out exactly nominal.
        proud = self.plate_thickness_m + BOOLEAN_OVERSHOOT
        tool_plate = trimesh.creation.cylinder(
            radius=self.tool_plate_diameter_m / 2.0, height=proud
        )
        tool_plate.apply_translation((0.0, 0.0, pivot_z + BOOLEAN_OVERSHOOT / 2.0))

        lean = (
            _translate((0.0, 0.0, pivot_z))
            @ trimesh.transformations.rotation_matrix(self.tilt_rad, (0.0, 1.0, 0.0))
            @ _translate((0.0, 0.0, -pivot_z))
        )
        tool_plate.apply_transform(lean)

        face_cut = trimesh.creation.box(extents=(0.5, 0.5, 0.5))
        face_cut.apply_translation((0.0, 0.0, face_z + 0.25))
        face_cut.apply_transform(lean)
        cuts.append(face_cut)

        body = trimesh.boolean.union([plate, post, tool_plate], engine=BOOLEAN_ENGINE)
        body = trimesh.boolean.difference([body, *cuts], engine=BOOLEAN_ENGINE)

        def leaned(local: tuple[float, float, float]) -> Pose:
            point = lean @ np.array([local[0], local[1], local[2], 1.0])
            return Pose(pos=tuple(float(v) for v in point[:3]), euler=(0.0, self.tilt_rad, 0.0))

        collision = [
            Primitive(
                role="flange_plate",
                shape="cylinder",
                size=(self.flange_diameter_m / 2.0, self.plate_thickness_m / 2.0),
                pose=Pose(pos=(0.0, 0.0, self.plate_thickness_m / 2.0)),
            ),
            Primitive(
                role="riser",
                shape="cylinder",
                size=(post_radius, (face_z - post_bottom) / 2.0),
                pose=Pose(pos=(0.0, 0.0, (post_bottom + face_z) / 2.0)),
            ),
            Primitive(
                role="tool_plate",
                shape="cylinder",
                size=(self.tool_plate_diameter_m / 2.0, self.plate_thickness_m / 2.0),
                pose=leaned((0.0, 0.0, pivot_z)),
            ),
        ]

        frames = {
            "mount": Pose(),
            "tool": leaned((0.0, 0.0, pivot_z + self.plate_thickness_m / 2.0)),
        }
        return self._finish(
            body,
            collision,
            frames,
            clearances={"bolt_hole": self.material.hole_allowance_m},
        )


class TubeRack(Part):
    """A block of wells that holds tubes upright.

    Sized from the tube, not from a catalogue: give it the tube diameter and the pitch you
    want, and it produces wells that accept the tube with the material's own allowance.
    """

    template: Literal["tube_rack"] = "tube_rack"

    rows: int = Field(default=2, ge=1, le=12)
    columns: int = Field(default=4, ge=1, le=12)
    pitch_m: float = Field(default=0.020, gt=0.005, le=0.06)
    tube_diameter_m: float = Field(default=0.011, gt=0.003, le=0.05)
    well_depth_m: float = Field(default=0.025, gt=0.004, le=0.12)
    wall_m: float = Field(default=0.003, gt=0.0008, le=0.02)
    floor_thickness_m: float = Field(default=0.004, gt=0.0015, le=0.03)
    well_clearance_m: float = Field(
        default=0.0005,
        ge=0.0,
        le=0.004,
        description="Radial slack so a tube drops in rather than being pressed in.",
    )

    @model_validator(mode="after")
    def wells_do_not_merge(self) -> "TubeRack":
        """Adjacent wells have to leave a divider between them, or the rack is one big hole."""
        well_diameter = self.tube_diameter_m + 2.0 * self.well_clearance_m
        divider = self.pitch_m - well_diameter
        wall = self.material.minimum_wall_m
        if (self.rows > 1 or self.columns > 1) and divider < wall:
            raise ValueError(
                f"a {self.pitch_m * 1000:.1f} mm pitch around {well_diameter * 1000:.1f} mm wells "
                f"leaves a {divider * 1000:.2f} mm divider, under the {wall * 1000:.2f} mm minimum "
                f"for {self.material.label}. Open up the pitch or use a narrower tube."
            )
        return self

    def build(self) -> PartGeometry:
        well_radius = self.tube_diameter_m / 2.0 + self.well_clearance_m
        span_x = (self.columns - 1) * self.pitch_m + 2.0 * (well_radius + self.wall_m)
        span_y = (self.rows - 1) * self.pitch_m + 2.0 * (well_radius + self.wall_m)
        height = self.well_depth_m + self.floor_thickness_m

        block = trimesh.creation.box(extents=(span_x, span_y, height))
        block.apply_translation((0.0, 0.0, height / 2.0))

        wells: list[trimesh.Trimesh] = []
        frames: dict[str, Pose] = {"base": Pose()}
        for row in range(self.rows):
            for column in range(self.columns):
                x = (column - (self.columns - 1) / 2.0) * self.pitch_m
                y = (row - (self.rows - 1) / 2.0) * self.pitch_m
                well = trimesh.creation.cylinder(
                    radius=well_radius, height=self.well_depth_m * 2.0
                )
                well.apply_translation((x, y, height))
                wells.append(well)
                frames[f"well.r{row}c{column}"] = Pose(pos=(x, y, height))

        body = trimesh.boolean.difference([block, *wells], engine=BOOLEAN_ENGINE)

        # The collision model is the block minus nothing: MuJoCo needs the well walls to be
        # solid so a tube can rest inside, and four wall slabs plus a floor represent that
        # exactly without a mesh collider.
        collision = _frame_walls(span_x, span_y, height, self.wall_m, self.floor_thickness_m)
        collision.extend(
            _well_dividers(self.rows, self.columns, self.pitch_m, well_radius, height, self.wall_m)
        )
        return self._finish(
            body,
            collision,
            frames,
            clearances={"well_radial": self.well_clearance_m},
        )


class Cradle(Part):
    """A negative-shaped seat that locates one specific object.

    Given the object's convex envelope, the seat is that envelope pushed outward by a
    clearance and cut into a block. This is the part that gets designed against a generated
    asset, which is why it takes the envelope as points rather than as a catalogue shape.
    """

    template: Literal["cradle"] = "cradle"

    target_extents_m: tuple[float, float, float] = Field(
        default=(0.06, 0.04, 0.03), description="Bounding extents of the object to be seated."
    )
    target_shape: Literal["box", "cylinder"] = "box"
    clearance_m: float = Field(default=0.001, ge=0.0, le=0.006)
    wall_m: float = Field(default=0.004, gt=0.0012, le=0.02)
    floor_thickness_m: float = Field(default=0.004, gt=0.0015, le=0.03)
    seat_depth_fraction: float = Field(
        default=0.6,
        gt=0.1,
        le=1.0,
        description="How much of the object's height the seat wraps. Deeper locates better "
        "but makes it harder for the arm to lift back out.",
    )

    def build(self) -> PartGeometry:
        tx, ty, tz = self.target_extents_m
        pocket_x = tx + 2.0 * self.clearance_m
        pocket_y = ty + 2.0 * self.clearance_m
        pocket_z = tz * self.seat_depth_fraction

        outer_x = pocket_x + 2.0 * self.wall_m
        outer_y = pocket_y + 2.0 * self.wall_m
        outer_z = pocket_z + self.floor_thickness_m

        block = trimesh.creation.box(extents=(outer_x, outer_y, outer_z))
        block.apply_translation((0.0, 0.0, outer_z / 2.0))

        if self.target_shape == "cylinder":
            pocket = trimesh.creation.cylinder(
                radius=max(pocket_x, pocket_y) / 2.0, height=pocket_z * 2.0
            )
        else:
            pocket = trimesh.creation.box(extents=(pocket_x, pocket_y, pocket_z * 2.0))
        pocket.apply_translation((0.0, 0.0, outer_z))

        body = trimesh.boolean.difference([block, pocket], engine=BOOLEAN_ENGINE)
        collision = _frame_walls(
            outer_x, outer_y, outer_z, self.wall_m, self.floor_thickness_m
        )
        frames = {
            "base": Pose(),
            "seat": Pose(pos=(0.0, 0.0, self.floor_thickness_m)),
            "seated_centre": Pose(pos=(0.0, 0.0, self.floor_thickness_m + tz / 2.0)),
        }
        return self._finish(body, collision, frames, clearances={"seat": self.clearance_m})


class PressFinger(Part):
    """A probe for pressing a button or a membrane switch.

    Held in the gripper rather than bolted to the flange, because that is what makes it
    usable without re-tooling: the shank is sized for the gripper's pads, and the tip is a
    sphere so contact force does not depend on how square the approach was.
    """

    template: Literal["press_finger"] = "press_finger"

    shank_width_m: float = Field(
        default=0.014, gt=0.005, le=0.04, description="Across the gripper's pads."
    )
    shank_thickness_m: float = Field(default=0.010, gt=0.004, le=0.03)
    shank_length_m: float = Field(default=0.030, gt=0.01, le=0.08)
    stem_length_m: float = Field(default=0.035, gt=0.005, le=0.15)
    stem_diameter_m: float = Field(default=0.008, gt=0.003, le=0.025)
    tip_radius_m: float = Field(default=0.005, gt=0.001, le=0.015)

    def build(self) -> PartGeometry:
        shank = trimesh.creation.box(
            extents=(self.shank_thickness_m, self.shank_width_m, self.shank_length_m)
        )
        shank.apply_translation((0.0, 0.0, self.shank_length_m / 2.0))

        stem = trimesh.creation.cylinder(
            radius=self.stem_diameter_m / 2.0, height=self.stem_length_m
        )
        stem.apply_translation((0.0, 0.0, self.shank_length_m + self.stem_length_m / 2.0))

        tip_z = self.shank_length_m + self.stem_length_m
        tip = trimesh.creation.icosphere(subdivisions=3, radius=self.tip_radius_m)
        tip.apply_translation((0.0, 0.0, tip_z))

        body = trimesh.boolean.union([shank, stem, tip], engine=BOOLEAN_ENGINE)
        collision = [
            Primitive(
                role="shank",
                shape="box",
                size=(
                    self.shank_thickness_m / 2.0,
                    self.shank_width_m / 2.0,
                    self.shank_length_m / 2.0,
                ),
                pose=Pose(pos=(0.0, 0.0, self.shank_length_m / 2.0)),
            ),
            Primitive(
                role="stem",
                shape="capsule",
                size=(self.stem_diameter_m / 2.0, self.stem_length_m / 2.0),
                pose=Pose(pos=(0.0, 0.0, self.shank_length_m + self.stem_length_m / 2.0)),
            ),
            Primitive(
                role="tip",
                shape="sphere",
                size=(self.tip_radius_m,),
                pose=Pose(pos=(0.0, 0.0, tip_z)),
            ),
        ]
        frames = {
            "grip": Pose(pos=(0.0, 0.0, self.shank_length_m / 2.0)),
            "mount": Pose(),
            "tip": Pose(pos=(0.0, 0.0, tip_z + self.tip_radius_m)),
        }
        return self._finish(body, collision, frames)


class LidHook(Part):
    """An L-shaped hook that catches a lid lip and swings it shut.

    Closing a lid by pushing on it with the gripper works until the lid is light enough to
    skitter. A hook constrains it in two directions instead of one, and needs no gripping
    force to hold, so the same motion works whether the lid is stiff or loose.
    """

    template: Literal["lid_hook"] = "lid_hook"

    shank_width_m: float = Field(default=0.014, gt=0.005, le=0.04)
    shank_thickness_m: float = Field(default=0.008, gt=0.003, le=0.025)
    shank_length_m: float = Field(default=0.030, gt=0.01, le=0.08)
    reach_m: float = Field(
        default=0.060, gt=0.01, le=0.2, description="From the gripped shank to the hook."
    )
    hook_depth_m: float = Field(
        default=0.012, gt=0.003, le=0.05, description="How far the hook drops past the lip."
    )
    hook_opening_m: float = Field(
        default=0.008, gt=0.002, le=0.04, description="Gap the lid lip has to fit through."
    )
    web_thickness_m: float = Field(default=0.005, gt=0.0016, le=0.02)

    def build(self) -> PartGeometry:
        shank = trimesh.creation.box(
            extents=(self.shank_thickness_m, self.shank_width_m, self.shank_length_m)
        )
        shank.apply_translation((0.0, 0.0, self.shank_length_m / 2.0))

        arm_length = self.reach_m
        arm = trimesh.creation.box(
            extents=(arm_length, self.shank_width_m, self.web_thickness_m)
        )
        arm_z = self.shank_length_m + self.web_thickness_m / 2.0
        arm.apply_translation((arm_length / 2.0, 0.0, arm_z))

        drop = trimesh.creation.box(
            extents=(self.web_thickness_m, self.shank_width_m, self.hook_depth_m)
        )
        drop_x = arm_length - self.web_thickness_m / 2.0
        drop.apply_translation((drop_x, 0.0, arm_z - self.hook_depth_m / 2.0))

        lip_z = arm_z - self.hook_depth_m
        lip = trimesh.creation.box(
            extents=(self.hook_opening_m + self.web_thickness_m, self.shank_width_m, self.web_thickness_m)
        )
        lip.apply_translation(
            (
                drop_x - (self.hook_opening_m + self.web_thickness_m) / 2.0,
                0.0,
                lip_z + self.web_thickness_m / 2.0,
            )
        )

        body = trimesh.boolean.union([shank, arm, drop, lip], engine=BOOLEAN_ENGINE)
        collision = [
            Primitive(
                role="shank",
                shape="box",
                size=(
                    self.shank_thickness_m / 2.0,
                    self.shank_width_m / 2.0,
                    self.shank_length_m / 2.0,
                ),
                pose=Pose(pos=(0.0, 0.0, self.shank_length_m / 2.0)),
            ),
            Primitive(
                role="arm",
                shape="box",
                size=(arm_length / 2.0, self.shank_width_m / 2.0, self.web_thickness_m / 2.0),
                pose=Pose(pos=(arm_length / 2.0, 0.0, arm_z)),
            ),
            Primitive(
                role="drop",
                shape="box",
                size=(
                    self.web_thickness_m / 2.0,
                    self.shank_width_m / 2.0,
                    self.hook_depth_m / 2.0,
                ),
                pose=Pose(pos=(drop_x, 0.0, arm_z - self.hook_depth_m / 2.0)),
            ),
            Primitive(
                role="lip",
                shape="box",
                size=(
                    (self.hook_opening_m + self.web_thickness_m) / 2.0,
                    self.shank_width_m / 2.0,
                    self.web_thickness_m / 2.0,
                ),
                pose=Pose(
                    pos=(
                        drop_x - (self.hook_opening_m + self.web_thickness_m) / 2.0,
                        0.0,
                        lip_z + self.web_thickness_m / 2.0,
                    )
                ),
            ),
        ]
        frames = {
            "grip": Pose(pos=(0.0, 0.0, self.shank_length_m / 2.0)),
            "mount": Pose(),
            "hook": Pose(pos=(drop_x - self.hook_opening_m / 2.0, 0.0, lip_z)),
        }
        return self._finish(
            body, collision, frames, clearances={"lip_opening": self.hook_opening_m}
        )


class BenchClamp(Part):
    """A C-clamp that pins something to the edge of the bench.

    Anything the arm pushes against has to be held down, and taping an instrument to a
    bench is how a repeatable layout stops being repeatable. The clamp gives a fixture a
    fixed, known position instead.
    """

    template: Literal["bench_clamp"] = "bench_clamp"

    bench_thickness_m: float = Field(default=0.040, gt=0.005, le=0.1)
    throat_depth_m: float = Field(
        default=0.035, gt=0.01, le=0.12, description="How far in from the bench edge it reaches."
    )
    jaw_thickness_m: float = Field(default=0.008, gt=0.002, le=0.03)
    width_m: float = Field(default=0.030, gt=0.008, le=0.1)
    web_thickness_m: float = Field(default=0.008, gt=0.003, le=0.03)
    clamp_clearance_m: float = Field(
        default=0.0005, ge=0.0, le=0.003, description="Slack over the bench thickness."
    )
    post_height_m: float = Field(
        default=0.020, ge=0.0, le=0.15, description="Post above the top jaw for a fixture to bolt to."
    )
    post_diameter_m: float = Field(default=0.016, gt=0.005, le=0.06)

    def build(self) -> PartGeometry:
        gap = self.bench_thickness_m + self.clamp_clearance_m
        total_height = gap + 2.0 * self.jaw_thickness_m

        def jaw(z_centre: float) -> trimesh.Trimesh:
            piece = trimesh.creation.box(
                extents=(self.throat_depth_m, self.width_m, self.jaw_thickness_m)
            )
            piece.apply_translation((self.throat_depth_m / 2.0, 0.0, z_centre))
            return piece

        bottom = jaw(self.jaw_thickness_m / 2.0)
        top = jaw(total_height - self.jaw_thickness_m / 2.0)
        web = trimesh.creation.box(
            extents=(self.web_thickness_m, self.width_m, total_height)
        )
        web.apply_translation((-self.web_thickness_m / 2.0, 0.0, total_height / 2.0))

        pieces = [bottom, top, web]
        if self.post_height_m > 0.0:
            post = trimesh.creation.cylinder(
                radius=self.post_diameter_m / 2.0, height=self.post_height_m
            )
            post.apply_translation(
                (self.throat_depth_m / 2.0, 0.0, total_height + self.post_height_m / 2.0)
            )
            pieces.append(post)

        body = trimesh.boolean.union(pieces, engine=BOOLEAN_ENGINE)
        collision = [
            Primitive(
                role="jaw_lower",
                shape="box",
                size=(self.throat_depth_m / 2.0, self.width_m / 2.0, self.jaw_thickness_m / 2.0),
                pose=Pose(pos=(self.throat_depth_m / 2.0, 0.0, self.jaw_thickness_m / 2.0)),
            ),
            Primitive(
                role="jaw_upper",
                shape="box",
                size=(self.throat_depth_m / 2.0, self.width_m / 2.0, self.jaw_thickness_m / 2.0),
                pose=Pose(
                    pos=(
                        self.throat_depth_m / 2.0,
                        0.0,
                        total_height - self.jaw_thickness_m / 2.0,
                    )
                ),
            ),
            Primitive(
                role="spine",
                shape="box",
                size=(self.web_thickness_m / 2.0, self.width_m / 2.0, total_height / 2.0),
                pose=Pose(pos=(-self.web_thickness_m / 2.0, 0.0, total_height / 2.0)),
            ),
        ]
        if self.post_height_m > 0.0:
            collision.append(
                Primitive(
                    shape="cylinder",
                    role="post",
                    size=(self.post_diameter_m / 2.0, self.post_height_m / 2.0),
                    pose=Pose(
                        pos=(
                            self.throat_depth_m / 2.0,
                            0.0,
                            total_height + self.post_height_m / 2.0,
                        )
                    ),
                )
            )

        frames = {
            "base": Pose(),
            "bench_edge": Pose(pos=(0.0, 0.0, self.jaw_thickness_m)),
            "post_top": Pose(pos=(self.throat_depth_m / 2.0, 0.0, total_height + self.post_height_m)),
        }
        return self._finish(
            body, collision, frames, clearances={"bench_fit": self.clamp_clearance_m}
        )


AnyPart = Annotated[
    FlangeAdapter | TubeRack | Cradle | PressFinger | LidHook | BenchClamp,
    Field(discriminator="template"),
]

TEMPLATES: dict[str, type[Part]] = {
    "flange_adapter": FlangeAdapter,
    "tube_rack": TubeRack,
    "cradle": Cradle,
    "press_finger": PressFinger,
    "lid_hook": LidHook,
    "bench_clamp": BenchClamp,
}


def template_schema(name: str) -> dict[str, object]:
    """The JSON schema for one template's parameters, for a model to fill in."""
    try:
        return TEMPLATES[name].model_json_schema()
    except KeyError:
        raise KeyError(
            f"unknown template {name!r}; available: {', '.join(sorted(TEMPLATES))}"
        ) from None


# --------------------------------------------------------------------------- #
# Shared collision decompositions
# --------------------------------------------------------------------------- #


def _frame_walls(
    outer_x: float, outer_y: float, outer_z: float, wall: float, floor: float
) -> list[Primitive]:
    """Four walls and a floor: the collision model of any open-topped box."""
    wall_height = outer_z - floor
    mid_z = floor + wall_height / 2.0
    return [
        # `floor` is named because a plan can require the part it places to be resting on
        # it, which is the difference between seated and perched on the rim.
        Primitive(
            role="floor",
            shape="box",
            size=(outer_x / 2.0, outer_y / 2.0, floor / 2.0),
            pose=Pose(pos=(0.0, 0.0, floor / 2.0)),
        ),
        Primitive(
            role="wall_x_low",
            shape="box",
            size=(wall / 2.0, outer_y / 2.0, wall_height / 2.0),
            pose=Pose(pos=(-(outer_x - wall) / 2.0, 0.0, mid_z)),
        ),
        Primitive(
            role="wall_x_high",
            shape="box",
            size=(wall / 2.0, outer_y / 2.0, wall_height / 2.0),
            pose=Pose(pos=((outer_x - wall) / 2.0, 0.0, mid_z)),
        ),
        Primitive(
            role="wall_y_low",
            shape="box",
            size=((outer_x - 2.0 * wall) / 2.0, wall / 2.0, wall_height / 2.0),
            pose=Pose(pos=(0.0, -(outer_y - wall) / 2.0, mid_z)),
        ),
        Primitive(
            role="wall_y_high",
            shape="box",
            size=((outer_x - 2.0 * wall) / 2.0, wall / 2.0, wall_height / 2.0),
            pose=Pose(pos=(0.0, (outer_y - wall) / 2.0, mid_z)),
        ),
    ]


def _well_dividers(
    rows: int, columns: int, pitch: float, well_radius: float, height: float, wall: float
) -> list[Primitive]:
    """The material between adjacent wells, as thin slabs.

    Without these a tube dropped into an interior well would fall straight through to a
    neighbour, because the outer frame alone does not separate them.
    """
    divider = pitch - 2.0 * well_radius
    if divider <= 1e-5:
        return []
    wall_height = height - wall
    mid_z = wall + wall_height / 2.0
    out: list[Primitive] = []
    for column in range(columns - 1):
        x = (column - (columns - 1) / 2.0 + 0.5) * pitch
        out.append(
            Primitive(
                role=f"divider_x{column}",
                shape="box",
                size=(divider / 2.0, (rows * pitch) / 2.0, wall_height / 2.0),
                pose=Pose(pos=(x, 0.0, mid_z)),
            )
        )
    for row in range(rows - 1):
        y = (row - (rows - 1) / 2.0 + 0.5) * pitch
        out.append(
            Primitive(
                role=f"divider_y{row}",
                shape="box",
                size=((columns * pitch) / 2.0, divider / 2.0, wall_height / 2.0),
                pose=Pose(pos=(0.0, y, mid_z)),
            )
        )
    return out


def _translate(offset: tuple[float, float, float]) -> np.ndarray:
    matrix = np.eye(4)
    matrix[:3, 3] = offset
    return matrix


def pose_from_matrix(matrix: np.ndarray) -> Pose:
    """Convert a homogeneous transform to a `Pose`, via the quaternion."""
    quat = matrix_to_quat(matrix[:3, :3])
    # MJCF takes a quaternion directly, but `Pose` carries Euler angles, so go through them.
    w, x, y, z = quat
    roll = math.atan2(2.0 * (w * x + y * z), 1.0 - 2.0 * (x * x + y * y))
    sin_pitch = max(-1.0, min(1.0, 2.0 * (w * y - z * x)))
    pitch = math.asin(sin_pitch)
    yaw = math.atan2(2.0 * (w * z + x * y), 1.0 - 2.0 * (y * y + z * z))
    return Pose(pos=tuple(float(v) for v in matrix[:3, 3]), euler=(roll, pitch, yaw))
