"""Executing an operation plan and recording it as a judgeable case.

The executor is intentionally dull. It holds one commanded control vector, and each action
does nothing but say where that vector should be by the time the action ends. Every step
interpolates towards it with a smoothstep ramp, integrates once, and records the state.
There is no per-device logic, no re-planning, no error recovery: if a `Move` cannot be
solved the action is still executed towards the best configuration the solver found, the
shortfall is recorded, and the judge is left to say whether the episode was acceptable.

The output is a `sim_judge` case bundle:

    <case>/bound-operation.json          judging policy, generated by `amx.sim.policy`
    <case>/task-execution.json           action spans and geom-to-entity bindings
    <case>/closed-scene/scene.xml        the composed scene, with its meshes
    <case>/raw-dynamics/raw-trace.json   recording manifest
    <case>/raw-dynamics/steps-*.npz      per-step states
    <case>/raw-dynamics/compiled-model.mjb
"""

from __future__ import annotations

import hashlib
import json
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import mujoco
import numpy as np

from amx.geometry import PoseTarget, euler_to_quat, quat_to_matrix, smoothstep
from amx.sim.gripper import calibrate
from amx.sim.kinematics import IkResult, joint_addresses, solve_site_pose
from amx.sim.plan import Actuate, Grip, Hold, Move, OperationPlan
from amx.sim.policy import build_policy, geometry_bindings
from amx.sim.scene import BuiltScene
from amx.sim.trace import TraceRecorder

GRIP_SETTLE_SECONDS = 1.0
"""How long to let a commanded grasp finish closing before moving on."""

GRIP_STILL_RAD_S = 5e-3
"""Below this, the fingers have arrived and the grasp is whatever it is going to be."""


class ExecutionError(RuntimeError):
    """The plan cannot be executed against this scene at all."""


@dataclass(frozen=True)
class ActionSpan:
    action_id: str
    step_id: str
    first_step: int
    step_count: int
    ik: IkResult | None = None

    def as_dict(self) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "action_id": self.action_id,
            "step_id": self.step_id,
            "first_step": self.first_step,
            "step_count": self.step_count,
        }
        if self.ik is not None:
            payload["ik"] = self.ik.as_dict()
        return payload


@dataclass
class BodyPose:
    """A body's world pose at one instant."""

    position: np.ndarray
    quaternion: np.ndarray


@dataclass
class EpisodeResult:
    """What one execution produced, and how well the arm actually tracked the plan."""

    case_dir: Path
    scene_path: Path
    step_count: int
    duration_s: float
    spans: list[ActionSpan]
    diverged_at_step: int | None = None
    warnings: list[str] = field(default_factory=list)

    subject_start: BodyPose | None = None
    """Where the manipulated part was before the arm moved, and where it ended up. Kept on
    the result so `amx.sim.outcome` can say whether the task happened without reloading the
    model and replaying the trace."""

    subject_final: BodyPose | None = None
    destination_xy: tuple[float, float] | None = None

    @property
    def unreached_moves(self) -> list[ActionSpan]:
        return [s for s in self.spans if s.ik is not None and not s.ik.converged]

    def summary(self) -> str:
        lines = [
            f"episode {self.case_dir.name}: {self.step_count} steps, {self.duration_s:.2f} s "
            f"over {len(self.spans)} actions"
        ]
        if self.diverged_at_step is not None:
            lines.append(f"  the integrator diverged at step {self.diverged_at_step}")
        for span in self.unreached_moves:
            assert span.ik is not None
            lines.append(
                f"  {span.action_id}: IK fell short by {span.ik.position_error_m * 1000:.2f} mm"
            )
        lines.extend(f"  {w}" for w in self.warnings)
        return "\n".join(lines)


def run_episode(
    built: BuiltScene,
    plan: OperationPlan,
    case_dir: Path,
    *,
    case_id: str = "case",
) -> EpisodeResult:
    """Execute `plan` in `built` and write a complete case bundle to `case_dir`."""
    case_dir = Path(case_dir)
    case_dir.mkdir(parents=True, exist_ok=True)

    model = built.load_model()
    data = mujoco.MjData(model)
    executor = _Executor(built, model, data, plan)
    recorder = TraceRecorder(model, case_dir / "raw-dynamics")

    executor.reset()
    subject_start = executor.subject_pose()
    spans, diverged = executor.play(recorder)
    subject_final = executor.subject_pose()

    case_sha256 = _case_digest(built, plan, case_id)
    recorder.finish(
        case_sha256=case_sha256,
        extra={"plan_id": plan.plan_id, "protocol_id": plan.protocol_id},
    )
    _copy_scene(built, case_dir / "closed-scene")

    _write_task_execution(
        case_dir / "task-execution.json",
        case_id=case_id,
        case_sha256=case_sha256,
        plan=plan,
        spans=spans,
        model=model,
    )
    policy = build_policy(built, plan, model, task_id=f"{plan.protocol_id}.{plan.plan_id}")
    (case_dir / "bound-operation.json").write_text(
        json.dumps(policy, indent=2, ensure_ascii=False) + "\n"
    )
    plan.write(case_dir / "operation-plan.json")

    result = EpisodeResult(
        case_dir=case_dir,
        scene_path=built.scene_path,
        step_count=recorder.step_count,
        duration_s=recorder.step_count * float(model.opt.timestep),
        spans=spans,
        diverged_at_step=diverged,
        warnings=executor.warnings,
        subject_start=subject_start,
        subject_final=subject_final,
        destination_xy=executor.destination_xy(),
    )
    (case_dir / "episode.json").write_text(
        json.dumps(
            {
                "case_id": case_id,
                "case_sha256": case_sha256,
                "step_count": result.step_count,
                "duration_s": result.duration_s,
                "diverged_at_step": diverged,
                "actions": [s.as_dict() for s in spans],
                "warnings": executor.warnings,
            },
            indent=2,
        )
        + "\n"
    )
    return result


class _Executor:
    """Turns actions into a control trajectory, one step at a time."""

    def __init__(
        self,
        built: BuiltScene,
        model: mujoco.MjModel,
        data: mujoco.MjData,
        plan: OperationPlan,
    ) -> None:
        self.built = built
        self.model = model
        self.data = data
        self.plan = plan
        self.warnings: list[str] = []
        self.warning_counts: dict[int, int] = {
            int(w): 0
            for w in (
                mujoco.mjtWarning.mjWARN_BADQPOS,
                mujoco.mjtWarning.mjWARN_BADQVEL,
                mujoco.mjtWarning.mjWARN_BADQACC,
                mujoco.mjtWarning.mjWARN_BADCTRL,
            )
        }

        robot = built.robot
        self.arm_actuators = np.array(
            [_actuator_id(model, name) for name in robot.arm_actuators], dtype=int
        )
        self.qpos_ids, self.dof_ids = joint_addresses(model, robot.arm_joints)
        self.gripper_actuators = np.array(
            [_actuator_id(model, a["name"]) for a in robot.gripper_actuators], dtype=int
        )
        _, self.gripper_dofs = joint_addresses(
            model, [a["joint"] for a in robot.gripper_actuators]
        )
        self.gripper_open, self.gripper_closed = robot.gripper_range()
        self.default_site = _site_id(model, robot.tcp_site)
        self.gripper = calibrate(
            model,
            joint_names=tuple(a["joint"] for a in robot.gripper_actuators),
            open_value=self.gripper_open,
            closed_value=self.gripper_closed,
            flange_body=robot.flange_body,
            namespace=robot.namespace,
        )

    def reset(self) -> None:
        """Start from the scene's home keyframe, with the servos already commanding it.

        Commanding the home configuration rather than zero matters: the servos would
        otherwise spend the first action hauling the arm from the pose in the keyframe
        towards straight-out, which is both a large unplanned motion and a singularity.
        """
        if self.model.nkey > 0:
            mujoco.mj_resetDataKeyframe(self.model, self.data, 0)
        else:
            mujoco.mj_resetData(self.model, self.data)
        for actuator, qpos_id in zip(self.arm_actuators, self.qpos_ids, strict=True):
            self.data.ctrl[actuator] = self.data.qpos[qpos_id]
        for actuator in self.gripper_actuators:
            self.data.ctrl[actuator] = self.gripper_open
        mujoco.mj_forward(self.model, self.data)

    def play(self, recorder: TraceRecorder) -> tuple[list ["ActionSpan"], int | None]:
        spans: list[ActionSpan] = []
        diverged: int | None = None

        for action in self.plan.actions:
            start = recorder.step_count
            target_ctrl = self.data.ctrl.copy()
            ik: IkResult | None = None

            if isinstance(action, Move):
                ik, target_ctrl = self._solve_move(action, target_ctrl)
            elif isinstance(action, Grip):
                target_ctrl[self.gripper_actuators] = self._grip_command(action)
            elif isinstance(action, Actuate):
                target_ctrl[_actuator_id(self.model, action.actuator)] = action.value
            elif not isinstance(action, Hold):
                raise ExecutionError(f"unsupported action {action!r}")

            diverged = self._ramp(recorder, action.step_id, target_ctrl, action.duration_s)
            if diverged is None and isinstance(action, Grip):
                diverged = self._close_fingers(recorder, action)
            spans.append(
                ActionSpan(
                    action_id=action.action_id,
                    step_id=action.step_id,
                    first_step=start,
                    step_count=recorder.step_count - start,
                    ik=ik,
                )
            )
            if diverged is not None:
                break

        if diverged is None and self.plan.settle_s > 0.0:
            start = recorder.step_count
            last_step_id = self.plan.actions[-1].step_id
            diverged = self._ramp(
                recorder, last_step_id, self.data.ctrl.copy(), self.plan.settle_s
            )
            spans.append(
                ActionSpan(
                    action_id="settle",
                    step_id=last_step_id,
                    first_step=start,
                    step_count=recorder.step_count - start,
                )
            )
        return spans, diverged

    def _compensate_gravity(self) -> None:
        """Feed the arm's own weight forward, the way a real controller does.

        Without this the servos have to produce the holding torque out of position error,
        and the error needed is large: the gains are sized for a given bandwidth, which
        makes them proportional to each joint's inertia, and the wrist joints have very
        little of that. A wrist gain of 8 N·m/rad holding half a newton-metre of gripper
        weight sits 60 mrad off its target — 8 mm at the tool, which closes the fingers
        beside a 10.8 mm tube rather than around it.

        No industrial arm works that way; they all feed forward the rigid-body dynamics and
        leave the feedback term to handle what is left. `qfrc_bias` is exactly that term
        already computed, so this is a subtraction rather than a model.
        """
        self.data.qfrc_applied[self.dof_ids] = self.data.qfrc_bias[self.dof_ids]

    def subject_pose(self) -> "BodyPose | None":
        """The manipulated part's pose right now, if the plan named one."""
        if not self.plan.manipulated_asset:
            return None
        namespace = self.built.asset_namespaces.get(self.plan.manipulated_asset)
        if namespace is None:
            return None
        body = mujoco.mj_name2id(
            self.model, mujoco.mjtObj.mjOBJ_BODY, f"{namespace}root_body"
        )
        if body < 0:
            body = _subtree_root(self.model, namespace)
        if body < 0:
            return None
        return BodyPose(
            # The centre of mass of the whole part, not the origin of its root body. Where
            # the origin sits is the model author's private choice — this tube's is at its
            # tip — so a height measured from it means nothing to a caller who did not
            # write the model. It cost a round: the tube stood correctly on the well floor
            # and was reported 15 mm too low, because 15 mm is where its author put zero.
            # A centre of mass needs no convention and includes the cap.
            position=self.data.subtree_com[body].copy(),
            quaternion=self.data.xquat[body].copy(),
        )

    def destination_xy(self) -> tuple[float, float] | None:
        destination = self.plan.destination
        if destination is None:
            return None
        site = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_SITE, destination.site)
        if site < 0:
            return None
        return (float(self.data.site_xpos[site][0]), float(self.data.site_xpos[site][1]))

    def _close_fingers(self, recorder: TraceRecorder, action: Grip) -> int | None:
        """Hold the command until the fingers stop moving.

        A `Grip` says how wide to hold the fingers, so it is finished when they are that
        wide — not when its nominal duration is up. The two are different because a gripper
        closing onto something decelerates as it makes contact, and the difference is not
        academic: a one-second grasp on this Robotiq left the pads still travelling when the
        next action began lifting, so the tube was dragged 10 mm down through the fingers
        and every later height in the plan was wrong by that much. The insert then drove it
        into the destination's floor.

        Bounded, because a gripper commanded onto something incompressible never quite
        stops. Reaching the bound is not an error — it is a firm grasp.
        """
        limit = int(GRIP_SETTLE_SECONDS / self.model.opt.timestep)
        held = self.data.ctrl.copy()
        for _ in range(limit):
            if float(np.abs(self.data.qvel[self.gripper_dofs]).max()) < GRIP_STILL_RAD_S:
                return None
            diverged = self._ramp(recorder, action.step_id, held, self.model.opt.timestep)
            if diverged is not None:
                return diverged
        self.warnings.append(
            f"{action.action_id}: the fingers were still moving after "
            f"{GRIP_SETTLE_SECONDS:.1f} s of settling; the grasp is being held against "
            "something that does not stop compressing"
        )
        return None

    def _grip_command(self, action: Grip) -> float:
        """The joint value that holds the pads `width_m` apart, per the measured gripper."""
        low, high = self.gripper.width_range_m
        if action.width_m > high:
            self.warnings.append(
                f"{action.action_id}: asked for a {action.width_m * 1000:.1f} mm opening but "
                f"the gripper only opens to {high * 1000:.1f} mm; holding it wide open"
            )
        return self.gripper.joint_for_width(min(max(action.width_m, low), high))

    def _solve_move(
        self, action: Move, target_ctrl: np.ndarray
    ) -> tuple[IkResult, np.ndarray]:
        site_id = self.default_site if not action.site else _site_id(self.model, action.site)
        position, rotation = self._resolve_target(action.target)
        result = solve_site_pose(
            self.model,
            site_id,
            position,
            rotation,
            dof_ids=self.dof_ids,
            qpos_ids=self.qpos_ids,
            seed_qpos=self.data.qpos.copy(),
        )
        if not result.converged:
            self.warnings.append(
                f"{action.action_id}: IK converged to {result.position_error_m * 1000:.2f} mm "
                f"of the target; executing towards the closest reachable configuration"
            )
        target_ctrl = target_ctrl.copy()
        target_ctrl[self.arm_actuators] = result.qpos[self.qpos_ids]
        return result, target_ctrl

    def _resolve_target(self, target: PoseTarget) -> tuple[np.ndarray, np.ndarray | None]:
        """Express a target in world coordinates, resolving a `frame` reference if given."""
        position = np.asarray(target.pos, dtype=float)
        rotation = (
            quat_to_matrix(euler_to_quat(target.euler)) if target.euler is not None else None
        )
        if target.frame:
            origin, basis = self._frame(target.frame)
            position = origin + basis @ position
            if rotation is not None:
                rotation = basis @ rotation
        return position, rotation

    def _frame(self, name: str) -> tuple[np.ndarray, np.ndarray]:
        site_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_SITE, name)
        if site_id >= 0:
            return self.data.site_xpos[site_id].copy(), self.data.site_xmat[site_id].reshape(3, 3).copy()
        body_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_BODY, name)
        if body_id >= 0:
            return self.data.xpos[body_id].copy(), self.data.xmat[body_id].reshape(3, 3).copy()
        raise ExecutionError(f"target frame {name!r} is neither a site nor a body in the scene")

    def _ramp(
        self,
        recorder: TraceRecorder,
        step_id: str,
        target_ctrl: np.ndarray,
        duration_s: float,
    ) -> int | None:
        """Interpolate the control vector to `target_ctrl` over `duration_s`, recording each step."""
        steps = max(1, int(round(duration_s / self.model.opt.timestep)))
        start_ctrl = self.data.ctrl.copy()
        for index in range(1, steps + 1):
            blend = smoothstep(index / steps)
            self.data.ctrl[:] = start_ctrl + blend * (target_ctrl - start_ctrl)
            self._compensate_gravity()
            before = recorder.state(self.data)
            mujoco.mj_step(self.model, self.data)
            after = recorder.state(self.data)
            recorder.record(before, after, step_id)
            reason = self._divergence()
            if reason:
                self.warnings.append(
                    f"the integrator diverged during {step_id} at step "
                    f"{recorder.step_count} ({reason}); the recording stops there"
                )
                return recorder.step_count
        return None

    def _divergence(self) -> str:
        """Whether the last step was physically meaningless, and why.

        Checking `qacc` for non-finite values is not enough, and the way it fails is nasty:
        when MuJoCo detects a bad position, velocity or acceleration it resets the whole
        `MjData` to the model's initial state and increments a warning counter. The step
        after a divergence therefore looks perfectly healthy — and looks, specifically, like
        the episode never happened, because everything is back where it started.

        That produced a run in which the arm picked the tube up, carried it across the
        bench, drove it 6 mm into the destination's floor, exploded to an angular speed of
        five million radians a second, and reported that the tube had moved 0.0 mm and was
        never picked up. The counters are the only reliable evidence, so they are what this
        reads.
        """
        for warning in (
            mujoco.mjtWarning.mjWARN_BADQPOS,
            mujoco.mjtWarning.mjWARN_BADQVEL,
            mujoco.mjtWarning.mjWARN_BADQACC,
            mujoco.mjtWarning.mjWARN_BADCTRL,
        ):
            count = int(self.data.warning[warning].number)
            if count > self.warning_counts[int(warning)]:
                self.warning_counts[int(warning)] = count
                return f"MuJoCo reported {warning.name} and reset the state"
        if not np.isfinite(self.data.qacc).all():
            return "the accelerations are no longer finite"
        return ""


def _actuator_id(model: mujoco.MjModel, name: str) -> int:
    found = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, name)
    if found < 0:
        raise ExecutionError(f"the scene has no actuator named {name!r}")
    return found


def _subtree_root(model: mujoco.MjModel, namespace: str) -> int:
    """The topmost body under `namespace` — the one the free joint moves."""
    best = -1
    best_depth = 1 << 30
    for body in range(model.nbody):
        name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, body)
        if not name or not name.startswith(namespace):
            continue
        depth = 0
        walk = body
        while walk > 0:
            walk = int(model.body_parentid[walk])
            depth += 1
        if depth < best_depth:
            best, best_depth = body, depth
    return best


def _site_id(model: mujoco.MjModel, name: str) -> int:
    found = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, name)
    if found < 0:
        raise ExecutionError(f"the scene has no site named {name!r}")
    return found


def _case_digest(built: BuiltScene, plan: OperationPlan, case_id: str) -> str:
    """A digest over the exact scene and plan that produced a recording.

    `sim_judge` uses it to pair a trace with the right entry in `task-execution.json`. It is
    derived rather than random so re-running an unchanged case reproduces the same bundle.
    """
    digest = hashlib.sha256()
    digest.update(case_id.encode())
    digest.update(built.scene_path.read_bytes())
    digest.update(json.dumps(plan.model_dump(mode="json"), sort_keys=True).encode())
    return digest.hexdigest()


def _copy_scene(built: BuiltScene, destination: Path) -> None:
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(built.scene_path.parent, destination)


def _write_task_execution(
    path: Path,
    *,
    case_id: str,
    case_sha256: str,
    plan: OperationPlan,
    spans: list[ActionSpan],
    model: mujoco.MjModel,
) -> None:
    payload = {
        "schema_version": "1.0",
        "protocol_id": plan.protocol_id,
        "cases": [
            {
                "case_id": case_id,
                "realization": {"case_sha256": case_sha256, "plan_id": plan.plan_id},
                "actions": [s.as_dict() for s in spans],
                "raw_dynamics": {"geometry_bindings": geometry_bindings(model)},
            }
        ],
    }
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
